# Deploy React/Vite app to GitHub Pages
name: Deploy Anonymous Website

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Create missing src folder and files
        run: |
          mkdir -p src
          mkdir -p public
          
          # Copy logo to public
          cp newestANONlogo.png public/
          
          # Create index.css (basic styles)
          echo '* { margin: 0; padding: 0; box-sizing: border-box; }' > src/index.css
          
          # Create main.tsx
          echo 'import React from "react"
          import ReactDOM from "react-dom/client"
          import App from "./App.tsx"
          import "./index.css"
          
          ReactDOM.createRoot(document.getElementById("root")!).render(
            <React.StrictMode>
              <App />
            </React.StrictMode>,
          )' > src/main.tsx
          
          # The App.tsx should already be uploaded - if not we'll create a basic one
          if [ ! -f "src/App.tsx" ]; then
            echo 'function App() { return <h1>Anonymous Website</h1>; } export default App;' > src/App.tsx
          fi
      
      - name: Install dependencies
        run: npm install
      
      - name: Fix Vite config
        run: |
          echo 'import { defineConfig } from "vite"
          import react from "@vitejs/plugin-react"
          
          export default defineConfig({
            plugins: [react()],
            base: "./"
          })' > vite.config.ts
      
      - name: Build React app
        run: npm run build
      
      - name: Setup Pages
        uses: actions/configure-pages@v5
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
